baseURL: "/"

title: indevn

theme: xmin

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    # - name: About
    #   url: ""
    #   weight: 2
    - name: Posts
      url: "posts/"
      weight: 3
    # - name: About
    #   url: "about/"
    #   weight: 2
    # - name: Categories
    #   url: "categories/"
    #   weight: 3
    # - name: Tags
    #   url: "tags/"
    #   weight: 4
    - name: GitHub
      url: "https://github.com/indevn/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [indevn](https://indevn.com) 2016 -- {Year} | [Github](https://github.com/indevn)"


# paginate: 3

enableEmoji: true
enableGitInfo: false
summaryLength: 75

defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir: false

# Uncomment for google analytics
# googleAnalytics: UA-123-45

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

build:
  useResourceCacheWhen: always